### ISSUE TITLE
Uncaught UnexpectedValueException: Wrong number of segments

### ISSUE THREAD

**Issue by SeanDez** [firebase/php-jwt#252]
This is the full stack trace I'm seeing on the webpage: 
```
Xdebug: Fatal error: Uncaught UnexpectedValueException: Wrong number of segments in
 /var/www/html/wptest2/wp-content/plugins/delayedCoupons/vendor/firebase/php-jwt/src/JWT.php:78
 Stack trace: #0 /var/www/html/wptest2/wp-
content/plugins/delayedCoupons/adminSettingsArea/Visitors.php(24):
 Firebase\JWT\JWT::decode('35', 'aromaHallSound', Array) #1 /var/www/html/wptest2/wp-
content/plugins/delayedCoupons/adminSettingsArea/Visitors.php(239): admin\controllers\Visitors-
>getVisitorIdCookie() #2 /var/www/html/wptest2/wp-includes/class-wp-hook.php(286):
 admin\controllers\Visitors->getOrSetVisitorCookie('') #3 /var/www/html/wptest2/wp-includes/class-
wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /var/www/html/wptest2/wp-
includes/plugin.php(465): WP_Hook->do_action(Array) #5 /var/www/html/wptest2/wp-
settings.php(505): do_action('init') #6 /var/www/html/wptest2/wp-config.php(97): 
require_once('/var/www/html/w...') #7 /var/www/html/wptest2/wp-load.php(37): 
require_once('/var/www/html/w...') #8 /var/www/html/wptest2/wp-admin/admin.php( in 
/var/www/html/wptest2/wp-content/plugins/delayedCoupons/vendor/firebase/php-jwt/src/JWT.php on
 line 78. Output triggered in /var/www/html/wptest2/wp-content/plugins/query-
monitor/collectors/php_errors.php on line 166
--
1 | 0.3031 | 6703568 | QM_Collector_PHP_Errors->shutdown_handler( ) | .../php_errors.php:0
2 | 0.3031 | 6707528 | xdebug_print_function_stack ( ??? ) | .../php_errors.php:166
```

The first method decodes, the 2nd method encodes. Prior to adding the JWT functionality both methods were correctly getting and setting cookies without error:

```
  protected function getVisitorIdCookie() : void {
    if (isset($_COOKIE['visitorId'])) {
      // decode() expects an object or array
      $decodedCookie = JWT::decode($_COOKIE['visitorId'], $this->Jwtkey, ['HS256'])[0];
      
      $this->visitorIdCookie = $decodedCookie;
    }
  }
  

  protected function createVisitorIdCookie() : void {
    global $wpdb;

    $highestVisitorId = $wpdb->get_var("SELECT MAX(visitorId) from {$wpdb->prefix}delayedCoupons_visits");
    
    $newIdForNewVisitor = intval($highestVisitorId) + 1;
    $this->visitorIdCookie = $newIdForNewVisitor;
    
    $tokenizedVisitorIdArray = JWT::encode([$newIdForNewVisitor], $this->Jwtkey);
    
    $setResult = setcookie(
      'visitorId'
      , "{$tokenizedVisitorIdArray}"
      , time() + (50 * 365 * 24 * 60 * 60)
      , '/'
      , null
      , null
      , true
    );
  }
```

The error is raised when I load any page that results in a server call to the above methods.

I'm running this locally on Php 7.2.15, Lubuntu 18.04 with Apache2. Thanks for any help.

**Comment by lindelius** [comment]
If you dump the value of the cookie (the encoded JWT), what do you get?

**Comment by SeanDez** [comment]
I would have clean out my current session so I hope you don't mind I did this test instead:

    $testDecode = JWT::encode(['testValue'], 'testKey'); 
    // value in debugger
    // eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.WyJ0ZXN0VmFsdWUiXQ.ADUxEd50vxYA8WJ56xxDUYlX6bQAejlvTciKpOYB-Ns

**Comment by SeanDez** [comment]
Solved, issue was an old unencoded cookie value was undesirably sent to decoded()
