### ISSUE TITLE
$keyOrKeyArray must be an instance of Firebase\JWT\Key

### ISSUE THREAD

**Issue by tegansnyder** [firebase/php-jwt#389]
I'm noticing that the most recent commit https://github.com/firebase/php-jwt/commit/edda0f9ee45b8367699804f792a9be6d5175e816 is causing a program that was working previously to fail with this error message:

```
Fatal error: Uncaught UnexpectedValueException: $keyOrKeyArray must be an instance of Firebase\JWT\Key key or an array of Firebase\JWT\Key keys in /vendor/firebase/php-jwt/src/JWT.php:416
Stack trace:
#0 /vendor/firebase/php-jwt/src/JWT.php(114): Firebase\JWT\JWT::getKey('-----BEGIN CERT...', NULL)
#1 app.php(422): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', '-----BEGIN CERT...', Array)
```

When I revert back to commit fbe639489d3348ff6e6d91f80b15198b39dc9217 it works fine. Just wanted to bring this to attention of maintainers.

I'm calling it like this:
```php
JWT::decode($jwt, $public_key, ['RS256']);
```
But it looks like the third param was removed by that commit:
![image](https://user-images.githubusercontent.com/1200195/149234495-58a802a3-264a-4429-95f9-9e824342c0b2.png)

I'm going to revert for now until I have some more time to properly look at what I need to do to be compatible with most recent commit.

**Comment by bshaffer** [comment]
Hello @tegansnyder! Thank you for reporting this.

This is working as designed. It looks like you are checking out to the `master` branch, which will soon break compatiblity with the previous version (`v5`). 

To prevent errors like this from happening, it's best to pin to a tag. The most recent tag is [v5.5.1](https://github.com/firebase/php-jwt/releases/tag/v5.5.1)

**Comment by tegansnyder** [comment]
Excellent thanks @bshaffer. Yep you are spot on, I didn't have this version pinned and it was pulling from master. Thanks again.

**Comment by ramammurshal** [comment]
Thank you mate
